plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'

yarnPath: .yarn/releases/yarn-2.0.0-rc.34.cjs

packageExtensions:
  react-scripts@3.4.1:
    dependencies:
      ts-pnp: '1.2.0'
  reactcss@*:
    dependencies:
      react: '16.13.1'
  react-color@2.18.1:
    dependencies:
      react: '16.13.1'
      '@icons/material': '0.4.1'
  ts-node-dev@1.0.0-pre.44:
    dependencies:
      typescript: '3.9.5'
