packageExtensions:
  react-scripts@*:
    dependencies:
      ts-pnp: "^1.2.0"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-2.3.1.cjs
