plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'

yarnPath: .yarn/releases/yarn-2.0.0-rc.34.cjs

packageExtensions:
  react-scripts@3.4.1:
    dependencies:
      ts-pnp: '1.2.0'
