FROM node:current

# Install packages
RUN apt update \
    && apt install -y --no-install-recommends \
        apt-transport-https \
        build-essential \
        ca-certificates \
        curl \
        git \
        gnupg-agent \
        libssl-dev \
        software-properties-common \
        wget \
        zsh \
    && curl -o- https://get.docker.com | bash \
    && apt clean \
    && curl -L "https://github.com/docker/compose/releases/download/1.24.1/docker-compose-$(uname -s)-$(uname -m)" \
        -o /usr/local/bin/docker-compose \
    && chmod +x /usr/local/bin/docker-compose \
    && curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash \
    && sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)" \
    && git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions

# Set the default shell to zsh
ENV SHELL /bin/zsh

# Copy zshrc with plugin config
COPY .devcontainer/.zshrc /root/.zshrc

WORKDIR /workspaces
