#!/bin/bash
# ==============================================================================
# Runs the NGINX daemon
# ==============================================================================
echo 'Starting NGINX...'
if [[ "${SSL}" = "true" ]]; then
    options='/etc/nginx/nginx-ssl.conf'
else
    options='/etc/nginx/nginx.conf'
fi

exec nginx -c "$options"