blank_issues_enabled: true
contact_links:
  - name: I have a question or need support
    url: https://github.com/timmo001/home-panel/discussions
    about: Please use the discussions area for getting help or asking questions.
