name: Request a new feature
description: Request a new feature or enhancement.
body:
  - type: textarea
    validations:
      required: true
    attributes:
      label: Description
      description: >-
        Details of the feature and what should be added.
  - type: textarea
    attributes:
      label: Additional information
      description: >
        If you have any additional information for us, use the field below.
        Please note, you can attach screenshots or screen recordings here, by
        dragging and dropping files in the field below.
