---
version: '3'

services:
  home-panel:
    image: timmo001/home-panel
    ports:
      - 3234:3234
      - 8234:8234
    volumes:
      - ~/ssl/fullchain.pem:/ssl/fullchain.pem
      - ~/ssl/privkey.pem:/ssl/privkey.pem
