---
version: '3'

services:
  home-panel:
    image: home-panel
    build: .
    environment:
      NODE_ENV: production
    ports:
      - 8234:443
    volumes:
      - ~/ssl:/ssl
  home-panel-api:
    image: timmo001/home-panel-api
    environment:
      CERTIFICATES_DIR: /ssl
    ports:
      - 3234:3234
    volumes:
      - ~/ssl:/ssl
