#!/usr/bin/with-contenv bash
# ==============================================================================
# Starts server to serve the API
# ==============================================================================
echo 'Run API..'

# shellcheck disable=SC2164
cd /opt/api

DB_PATH=/data/home-panel.db
CONFIG_PATH=/data/config.json

export DB_PATH
export CONFIG_PATH
export SSL_PATH_CERT
export SSL_PATH_KEY

exec node index.js